# Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:
    # Triangle      Tn = n * (n + 1) / 2    1, 3, 6, 10, 15, ...
    # Pentagonal    Pn = n * (3n − 1) / 2   1, 5, 12, 22, 35, ...
    # Hexagonal     Hn = n * (2n − 1)       1, 6, 15, 28, 45, ...

# It can be verified that T285 = P165 = H143 = 40755.

# Find the next triangle number that is also pentagonal and hexagonal.

triangles, pentagons, hexagons, count = set(), set(), set(), 100000

for n in range(count):
    triangles.add(int(n * (n + 1) / 2))
    pentagons.add(int(n * (3 * n - 1) / 2))
    hexagons.add(int(n * (2 * n - 1)))

for t in triangles:
    if t in pentagons and t in hexagons and t > 40755:
        print(t)
        break
